# thymeleaf
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecfpxt2
    username: root
    password: 159786
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mvc:
    static-path-pattern: /static/**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 80
    # �Ȳ������� ���
#  devtools:
#    restart:
#      enabled: true  #�Ȳ��� ��Ч
#      additional-paths: src/main/java  #�Ȳ��������Ŀ¼
#      exclude: static/** ,templates/**  # �ų���Щ Ŀ¼�ļ� ����Ҫ restart